const {
    PORT = 5000,
    NODE_ENV,
    API_KEY,
    API_SECRET,
    ZOOM_API_BASE_URL,
    WEBINARS_USER_ID,
    AK_USERNAME,
    AK_PASSWORD,
    ZOOM_350_ORG_USER_ID,
    AFRICA_USER_ID,
    EUROPE_ADMIN_USER_ID,
} = process.env

module.exports = {
    PORT,
    NODE_ENV,
    API_KEY,
    API_SECRET,
    ZOOM_API_BASE_URL,
    WEBINARS_USER_ID,
    AK_PASSWORD,
    AK_USERNAME,
    ZOOM_350_ORG_USER_ID,
    AFRICA_USER_ID,
    EUROPE_ADMIN_USER_ID
}